### ISSUE TITLE
服务器文件系统被创烂

### ISSUE THREAD

**Issue by SiriusNEO** [ACMClassOJ/TesutoHime#19]
原因暂不明，怀疑对象：
https://acm.sjtu.edu.cn/OnlineJudge/code?submit_id=219335

**Comment by LauYeeYu** [comment]
或许是由于大量读写文件导致的（服务器主机的文件系统不稳定）。<https://github.com/ACMClassOJ/TesutoHime/commit/6b1798be37982ef2b1b37fb60a02eee8957232d3> 缓解了此问题（通过限制输出文件大小）。
