### ISSUE TITLE
[Checker] Implement an efficient checker

### ISSUE THREAD

**Issue by Alan-Liang** [ACMClassOJ/TesutoHime#22]
`diff -qZB` has very poor performance when the two files compared differ wildly (the analysis of it's time complexity is left as an exercise to the reader). For example, comparing two files with 5,000,000 lines takes 159 seconds on my machine. This is unacceptable as it wastes task runner resources and causes congestion.

We need to implement a custom checker that matches the behavior of `diff -qZB` while being efficient. There is no such checker in testlib.

**Comment by LauYeeYu** [comment]
<https://github.com/ACMClassOJ/TesutoHime/commit/555914ad9dc66508d36c908bf8dfa026cd230bd9> implements an checker. (But not tested yet.)

**Comment by LauYeeYu** [comment]
After A/B testing the checker for serveral months, we finally use the efficient checker only and deprecate `diff -qZB` (1c04f1b27da2190d2ff2969881f46528840c8d23).

For more information about the new checker, see [this post](https://acm.sjtu.edu.cn/OnlineJudge/blog/new-efficient-file-checker/).
